version: '3.2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:5000'
    env_file: .env
  # minio:
  #   image: minio/minio
  #   volumes:
  #     - ./data:/data
  #   ports:
  #     - 9000:9000
  #   environment:
  #     - MINIO_ACCESS_KEY=
  #     - MINIO_SECRET_KEY=
