version: "3.2"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:5000
    env_file: .env
    network_mode: "host"
  storage:
    image: minio/minio
    volumes:
      - ./data:/data
    ports:
      - ${MINIO_PORT}:9000
    network_mode: "host"
    command: server /data
